### ISSUE TITLE
Create binary

### ISSUE THREAD

**Issue by huerlisi** [koffeinfrei/technologist#6]
While running the detector from the Ruby console or some application is powerfull, we should also provide a binary.

**Comment by huerlisi** [comment]
I'm currently experimenting with Thor to build such a simple binary. Keep you posted...

**Comment by koffeinfrei** [comment]
Maybe have a look at https://github.com/github/linguist/blob/master/bin/linguist e.g. Thor is a bit overkill IMO, as for now we don't need any params except the repo path.
Besides, Thor is a great fit if you have an applications with subcommands (as e.g. git). For a simple option parser i like https://github.com/leejarvis/slop.

**Comment by huerlisi** [comment]
Cool, thanks.
