### ISSUE TITLE
Consider changing license to MIT or AGPL

### ISSUE THREAD

**Issue by huerlisi** [koffeinfrei/technologist#8]
Looking at the functionality this project provides (determine frameworks in projects) I can imagine web services wanting to use it.

This makes GPL not the best choice of license:
* if the copyleft effect is wanted then internal forks for webservices are allowed and therefore AGPL should be used
* if the license should support widespread adaption, MIT would be a better fit

**Comment by koffeinfrei** [comment]
> if the copyleft effect is wanted then internal forks for webservices are allowed and therefore AGPL should be used

As far is I understand, the mentioned case for AGPL targets web applications and forks thereof themselves. As this is a library, a web services / application using this library must be GPL-compatible and therefore this gem doesn't need AGPL. Maybe I got that wrong, but with your argument everything should be released under the AGPL and the GPL has no use anymore.

> if the license should support widespread adaption, MIT would be a better fit

Widespread adoption (OSS) vs Free Software (FOSS), I choose the latter. Projects using this gem should be published as free software as well.

**Comment by huerlisi** [comment]
I'm with you regarding FOSS :-)

I see the AGPL vs. GPL also in the light of #6. When we introduce a binary that might well be used instead of GPL which would negate the linking argument. Therefore the server aspect gets relevant.

**Comment by koffeinfrei** [comment]
Right. I'll change it to AGPL then.
(From now on I'll just release everything under the AGPL instead of the GPL)

**Comment by koffeinfrei** [comment]
Fixed in https://github.com/koffeinfrei/technologist/commit/e6812bb2c6641671490122591b6ee005e56ab1a0
